apiVersion: v2
name: hello-app-chart
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

appVersion: v0.3

dependencies:
  - name: postgresql
    version: 9.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database
